library:
  source-dirs: src
tests:
  haskTodo-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskTodo
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- base >= 4.7 && < 5
name: haskTodo
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/haskTodo
license: BSD3
executables:
  haskTodo-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - haskTodo
description: Please see the README on GitHub at <https://github.com/githubuser/haskTodo#readme>
